name: "Create Or Update Unique Issue"
description: "Create or Update Unique Issue Action"

inputs:
  token:
    description: "GITHUB_TOKEN or a repo scoped PAT"
    default: ${{ github.token }}
  title:
    description: "The title of the issue to create or update"
    required: true
  body:
    description: "The body of the issue to create or update"
    required: true
  unique-title-includes:
    description: "The unique title to search for in the repository"
    required: true
  close:
    description: "Close the comment or skip creation"
    default: "false"

outputs:
  issue-number:
    description: "The ID of the issue created or updated"
    value: ${{ steps.result.outputs.issue-number }}

runs:
  using: "composite"
  steps:
    - name: Find issue
      id: find-issue
      uses: actions-cool/issues-helper@v3
      with:
        token: ${{ inputs.token }}
        actions: "find-issues"
        title-includes: ${{ inputs.unique-title-includes }}

    - name: Get issue number
      shell: bash
      id: get-issue-number
      run: |
        issues=$(cat <<EOF
        ${{ steps.find-issue.outputs.issues }}
        EOF
        )
        if [ "$issues" != "[]" ]; then
          echo "issue-number=$(echo $issues | jq -r '.[0].number')" >> $GITHUB_OUTPUT
        fi

    - name: Create Issue
      if: steps.get-issue-number.outputs.issue-number == '' && inputs.close != 'true'
      id: create-issue
      uses: actions-cool/issues-helper@v3
      with:
        token: ${{ inputs.token }}
        actions: "create-issue"
        title: ${{ inputs.title }}
        body: ${{ inputs.body }}

    - name: Update Issue
      if: steps.get-issue-number.outputs.issue-number != ''
      id: update-issue
      uses: actions-cool/issues-helper@v3
      with:
        token: ${{ inputs.token }}
        actions: "update-issue"
        issue-number: ${{ steps.get-issue-number.outputs.issue-number }}
        title: ${{ inputs.title }}
        body: ${{ inputs.body }}

    - name: Close Issue
      if: steps.get-issue-number.outputs.issue-number != '' && inputs.close == 'true'
      id: close-issue
      uses: actions-cool/issues-helper@v3
      with:
        token: ${{ inputs.token }}
        actions: "close-issue"
        issue-number: ${{ steps.get-issue-number.outputs.issue-number }}
        close-reason: "not_planned"

    - name: Result
      shell: bash
      id: result
      run: |
        if [ -n "${{ steps.get-issue-number.outputs.issue-number }}" ]; then
          echo "issue-number=${{ steps.get-issue-number.outputs.issue-number }}" >> $GITHUB_OUTPUT
        elif [ -n "${{ steps.create-issue.outputs.issue-number }}" ]; then
          echo "issue-number=${{ steps.create-issue.outputs.issue-number }}" >> $GITHUB_OUTPUT
        fi

branding:
  icon: "check-square"
  color: "gray-dark"
